class AppCurrency {
  const AppCurrency({
    required this.code,
    required this.symbol,
    required this.name,
  });

  final String code;
  final String symbol;
  final String name;

  String get label => '$name ($symbol $code)';
}

class AppCountry {
  const AppCountry({
    required this.code,
    required this.name,
    required this.currencyCode,
  });

  final String code;
  final String name;
  final String currencyCode;

  AppCurrency get currency => AppCurrencies.byCode(currencyCode);
}

abstract final class AppCurrencies {
  static const currencies = <AppCurrency>[
    AppCurrency(code: 'AED', symbol: 'د.إ', name: 'UAE Dirham'),
    AppCurrency(code: 'AFN', symbol: '؋', name: 'Afghan Afghani'),
    AppCurrency(code: 'ALL', symbol: 'L', name: 'Albanian Lek'),
    AppCurrency(code: 'AMD', symbol: '֏', name: 'Armenian Dram'),
    AppCurrency(code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder'),
    AppCurrency(code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza'),
    AppCurrency(code: 'ARS', symbol: r'$', name: 'Argentine Peso'),
    AppCurrency(code: 'AUD', symbol: r'A$', name: 'Australian Dollar'),
    AppCurrency(code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin'),
    AppCurrency(code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat'),
    AppCurrency(code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark'),
    AppCurrency(code: 'BBD', symbol: r'Bds$', name: 'Barbadian Dollar'),
    AppCurrency(code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka'),
    AppCurrency(code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev'),
    AppCurrency(code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar'),
    AppCurrency(code: 'BIF', symbol: 'FBu', name: 'Burundian Franc'),
    AppCurrency(code: 'BMD', symbol: r'BD$', name: 'Bermudian Dollar'),
    AppCurrency(code: 'BND', symbol: r'B$', name: 'Brunei Dollar'),
    AppCurrency(code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano'),
    AppCurrency(code: 'BRL', symbol: r'R$', name: 'Brazilian Real'),
    AppCurrency(code: 'BSD', symbol: r'B$', name: 'Bahamian Dollar'),
    AppCurrency(code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum'),
    AppCurrency(code: 'BWP', symbol: 'P', name: 'Botswana Pula'),
    AppCurrency(code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble'),
    AppCurrency(code: 'BZD', symbol: r'BZ$', name: 'Belize Dollar'),
    AppCurrency(code: 'CAD', symbol: r'C$', name: 'Canadian Dollar'),
    AppCurrency(code: 'CDF', symbol: 'FC', name: 'Congolese Franc'),
    AppCurrency(code: 'CHF', symbol: 'CHF', name: 'Swiss Franc'),
    AppCurrency(code: 'CLP', symbol: r'$', name: 'Chilean Peso'),
    AppCurrency(code: 'CNY', symbol: '¥', name: 'Chinese Yuan'),
    AppCurrency(code: 'COP', symbol: r'$', name: 'Colombian Peso'),
    AppCurrency(code: 'CRC', symbol: '₡', name: 'Costa Rican Colón'),
    AppCurrency(code: 'CUP', symbol: r'$', name: 'Cuban Peso'),
    AppCurrency(code: 'CVE', symbol: r'$', name: 'Cape Verdean Escudo'),
    AppCurrency(code: 'CZK', symbol: 'Kč', name: 'Czech Koruna'),
    AppCurrency(code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc'),
    AppCurrency(code: 'DKK', symbol: 'kr', name: 'Danish Krone'),
    AppCurrency(code: 'DOP', symbol: r'RD$', name: 'Dominican Peso'),
    AppCurrency(code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar'),
    AppCurrency(code: 'EGP', symbol: 'E£', name: 'Egyptian Pound'),
    AppCurrency(code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa'),
    AppCurrency(code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr'),
    AppCurrency(code: 'EUR', symbol: '€', name: 'Euro'),
    AppCurrency(code: 'FJD', symbol: r'FJ$', name: 'Fijian Dollar'),
    AppCurrency(code: 'FKP', symbol: '£', name: 'Falkland Islands Pound'),
    AppCurrency(code: 'GBP', symbol: '£', name: 'British Pound'),
    AppCurrency(code: 'GEL', symbol: '₾', name: 'Georgian Lari'),
    AppCurrency(code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi'),
    AppCurrency(code: 'GIP', symbol: '£', name: 'Gibraltar Pound'),
    AppCurrency(code: 'GMD', symbol: 'D', name: 'Gambian Dalasi'),
    AppCurrency(code: 'GNF', symbol: 'FG', name: 'Guinean Franc'),
    AppCurrency(code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal'),
    AppCurrency(code: 'GYD', symbol: r'G$', name: 'Guyanese Dollar'),
    AppCurrency(code: 'HKD', symbol: r'HK$', name: 'Hong Kong Dollar'),
    AppCurrency(code: 'HNL', symbol: 'L', name: 'Honduran Lempira'),
    AppCurrency(code: 'HTG', symbol: 'G', name: 'Haitian Gourde'),
    AppCurrency(code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint'),
    AppCurrency(code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah'),
    AppCurrency(code: 'ILS', symbol: '₪', name: 'Israeli Shekel'),
    AppCurrency(code: 'INR', symbol: '₹', name: 'Indian Rupee'),
    AppCurrency(code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar'),
    AppCurrency(code: 'IRR', symbol: '﷼', name: 'Iranian Rial'),
    AppCurrency(code: 'ISK', symbol: 'kr', name: 'Icelandic Króna'),
    AppCurrency(code: 'JMD', symbol: r'J$', name: 'Jamaican Dollar'),
    AppCurrency(code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar'),
    AppCurrency(code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
    AppCurrency(code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling'),
    AppCurrency(code: 'KGS', symbol: 'с', name: 'Kyrgyzstani Som'),
    AppCurrency(code: 'KHR', symbol: '៛', name: 'Cambodian Riel'),
    AppCurrency(code: 'KMF', symbol: 'CF', name: 'Comorian Franc'),
    AppCurrency(code: 'KPW', symbol: '₩', name: 'North Korean Won'),
    AppCurrency(code: 'KRW', symbol: '₩', name: 'South Korean Won'),
    AppCurrency(code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar'),
    AppCurrency(code: 'KYD', symbol: r'CI$', name: 'Cayman Islands Dollar'),
    AppCurrency(code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge'),
    AppCurrency(code: 'LAK', symbol: '₭', name: 'Lao Kip'),
    AppCurrency(code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound'),
    AppCurrency(code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee'),
    AppCurrency(code: 'LRD', symbol: r'L$', name: 'Liberian Dollar'),
    AppCurrency(code: 'LSL', symbol: 'L', name: 'Lesotho Loti'),
    AppCurrency(code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar'),
    AppCurrency(code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham'),
    AppCurrency(code: 'MDL', symbol: 'L', name: 'Moldovan Leu'),
    AppCurrency(code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary'),
    AppCurrency(code: 'MKD', symbol: 'ден', name: 'Macedonian Denar'),
    AppCurrency(code: 'MMK', symbol: 'K', name: 'Myanmar Kyat'),
    AppCurrency(code: 'MNT', symbol: '₮', name: 'Mongolian Tögrög'),
    AppCurrency(code: 'MOP', symbol: r'MOP$', name: 'Macanese Pataca'),
    AppCurrency(code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya'),
    AppCurrency(code: 'MUR', symbol: '₨', name: 'Mauritian Rupee'),
    AppCurrency(code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa'),
    AppCurrency(code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha'),
    AppCurrency(code: 'MXN', symbol: r'$', name: 'Mexican Peso'),
    AppCurrency(code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit'),
    AppCurrency(code: 'MZN', symbol: 'MT', name: 'Mozambican Metical'),
    AppCurrency(code: 'NAD', symbol: r'N$', name: 'Namibian Dollar'),
    AppCurrency(code: 'NGN', symbol: '₦', name: 'Nigerian Naira'),
    AppCurrency(code: 'NIO', symbol: r'C$', name: 'Nicaraguan Córdoba'),
    AppCurrency(code: 'NOK', symbol: 'kr', name: 'Norwegian Krone'),
    AppCurrency(code: 'NPR', symbol: 'रू', name: 'Nepalese Rupee'),
    AppCurrency(code: 'NZD', symbol: r'NZ$', name: 'New Zealand Dollar'),
    AppCurrency(code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial'),
    AppCurrency(code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa'),
    AppCurrency(code: 'PEN', symbol: 'S/', name: 'Peruvian Sol'),
    AppCurrency(code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina'),
    AppCurrency(code: 'PHP', symbol: '₱', name: 'Philippine Peso'),
    AppCurrency(code: 'PKR', symbol: '₨', name: 'Pakistani Rupee'),
    AppCurrency(code: 'PLN', symbol: 'zł', name: 'Polish Zloty'),
    AppCurrency(code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani'),
    AppCurrency(code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal'),
    AppCurrency(code: 'RON', symbol: 'lei', name: 'Romanian Leu'),
    AppCurrency(code: 'RSD', symbol: 'дин', name: 'Serbian Dinar'),
    AppCurrency(code: 'RUB', symbol: '₽', name: 'Russian Ruble'),
    AppCurrency(code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc'),
    AppCurrency(code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal'),
    AppCurrency(code: 'SBD', symbol: r'SI$', name: 'Solomon Islands Dollar'),
    AppCurrency(code: 'SCR', symbol: '₨', name: 'Seychellois Rupee'),
    AppCurrency(code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound'),
    AppCurrency(code: 'SEK', symbol: 'kr', name: 'Swedish Krona'),
    AppCurrency(code: 'SGD', symbol: r'S$', name: 'Singapore Dollar'),
    AppCurrency(code: 'SHP', symbol: '£', name: 'Saint Helena Pound'),
    AppCurrency(code: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone'),
    AppCurrency(code: 'SOS', symbol: 'Sh', name: 'Somali Shilling'),
    AppCurrency(code: 'SRD', symbol: r'$', name: 'Surinamese Dollar'),
    AppCurrency(code: 'SSP', symbol: '£', name: 'South Sudanese Pound'),
    AppCurrency(code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra'),
    AppCurrency(code: 'SYP', symbol: '£', name: 'Syrian Pound'),
    AppCurrency(code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni'),
    AppCurrency(code: 'THB', symbol: '฿', name: 'Thai Baht'),
    AppCurrency(code: 'TJS', symbol: 'ЅМ', name: 'Tajikistani Somoni'),
    AppCurrency(code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat'),
    AppCurrency(code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar'),
    AppCurrency(code: 'TOP', symbol: r'T$', name: 'Tongan Paʻanga'),
    AppCurrency(code: 'TRY', symbol: '₺', name: 'Turkish Lira'),
    AppCurrency(code: 'TTD', symbol: r'TT$', name: 'Trinidad and Tobago Dollar'),
    AppCurrency(code: 'TWD', symbol: r'NT$', name: 'New Taiwan Dollar'),
    AppCurrency(code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling'),
    AppCurrency(code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia'),
    AppCurrency(code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling'),
    AppCurrency(code: 'USD', symbol: r'$', name: 'US Dollar'),
    AppCurrency(code: 'UYU', symbol: r'$U', name: 'Uruguayan Peso'),
    AppCurrency(code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som'),
    AppCurrency(code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar'),
    AppCurrency(code: 'VND', symbol: '₫', name: 'Vietnamese Dong'),
    AppCurrency(code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu'),
    AppCurrency(code: 'WST', symbol: 'T', name: 'Samoan Tala'),
    AppCurrency(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc'),
    AppCurrency(code: 'XCD', symbol: r'EC$', name: 'East Caribbean Dollar'),
    AppCurrency(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc'),
    AppCurrency(code: 'XPF', symbol: '₣', name: 'CFP Franc'),
    AppCurrency(code: 'YER', symbol: '﷼', name: 'Yemeni Rial'),
    AppCurrency(code: 'ZAR', symbol: 'R', name: 'South African Rand'),
    AppCurrency(code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha'),
    AppCurrency(code: 'ZWG', symbol: 'ZiG', name: 'Zimbabwe Gold'),
  ];

  static const countries = <AppCountry>[
    AppCountry(code: 'AF', name: 'Afghanistan', currencyCode: 'AFN'),
    AppCountry(code: 'AL', name: 'Albania', currencyCode: 'ALL'),
    AppCountry(code: 'DZ', name: 'Algeria', currencyCode: 'DZD'),
    AppCountry(code: 'AD', name: 'Andorra', currencyCode: 'EUR'),
    AppCountry(code: 'AO', name: 'Angola', currencyCode: 'AOA'),
    AppCountry(code: 'AG', name: 'Antigua and Barbuda', currencyCode: 'XCD'),
    AppCountry(code: 'AR', name: 'Argentina', currencyCode: 'ARS'),
    AppCountry(code: 'AM', name: 'Armenia', currencyCode: 'AMD'),
    AppCountry(code: 'AU', name: 'Australia', currencyCode: 'AUD'),
    AppCountry(code: 'AT', name: 'Austria', currencyCode: 'EUR'),
    AppCountry(code: 'AZ', name: 'Azerbaijan', currencyCode: 'AZN'),
    AppCountry(code: 'BS', name: 'Bahamas', currencyCode: 'BSD'),
    AppCountry(code: 'BH', name: 'Bahrain', currencyCode: 'BHD'),
    AppCountry(code: 'BD', name: 'Bangladesh', currencyCode: 'BDT'),
    AppCountry(code: 'BB', name: 'Barbados', currencyCode: 'BBD'),
    AppCountry(code: 'BY', name: 'Belarus', currencyCode: 'BYN'),
    AppCountry(code: 'BE', name: 'Belgium', currencyCode: 'EUR'),
    AppCountry(code: 'BZ', name: 'Belize', currencyCode: 'BZD'),
    AppCountry(code: 'BJ', name: 'Benin', currencyCode: 'XOF'),
    AppCountry(code: 'BT', name: 'Bhutan', currencyCode: 'BTN'),
    AppCountry(code: 'BO', name: 'Bolivia', currencyCode: 'BOB'),
    AppCountry(code: 'BA', name: 'Bosnia and Herzegovina', currencyCode: 'BAM'),
    AppCountry(code: 'BW', name: 'Botswana', currencyCode: 'BWP'),
    AppCountry(code: 'BR', name: 'Brazil', currencyCode: 'BRL'),
    AppCountry(code: 'BN', name: 'Brunei', currencyCode: 'BND'),
    AppCountry(code: 'BG', name: 'Bulgaria', currencyCode: 'BGN'),
    AppCountry(code: 'BF', name: 'Burkina Faso', currencyCode: 'XOF'),
    AppCountry(code: 'BI', name: 'Burundi', currencyCode: 'BIF'),
    AppCountry(code: 'CV', name: 'Cabo Verde', currencyCode: 'CVE'),
    AppCountry(code: 'KH', name: 'Cambodia', currencyCode: 'KHR'),
    AppCountry(code: 'CM', name: 'Cameroon', currencyCode: 'XAF'),
    AppCountry(code: 'CA', name: 'Canada', currencyCode: 'CAD'),
    AppCountry(code: 'CF', name: 'Central African Republic', currencyCode: 'XAF'),
    AppCountry(code: 'TD', name: 'Chad', currencyCode: 'XAF'),
    AppCountry(code: 'CL', name: 'Chile', currencyCode: 'CLP'),
    AppCountry(code: 'CN', name: 'China', currencyCode: 'CNY'),
    AppCountry(code: 'CO', name: 'Colombia', currencyCode: 'COP'),
    AppCountry(code: 'KM', name: 'Comoros', currencyCode: 'KMF'),
    AppCountry(code: 'CG', name: 'Congo', currencyCode: 'XAF'),
    AppCountry(code: 'CD', name: 'Congo (DRC)', currencyCode: 'CDF'),
    AppCountry(code: 'CR', name: 'Costa Rica', currencyCode: 'CRC'),
    AppCountry(code: 'CI', name: 'Côte d’Ivoire', currencyCode: 'XOF'),
    AppCountry(code: 'HR', name: 'Croatia', currencyCode: 'EUR'),
    AppCountry(code: 'CU', name: 'Cuba', currencyCode: 'CUP'),
    AppCountry(code: 'CY', name: 'Cyprus', currencyCode: 'EUR'),
    AppCountry(code: 'CZ', name: 'Czechia', currencyCode: 'CZK'),
    AppCountry(code: 'DK', name: 'Denmark', currencyCode: 'DKK'),
    AppCountry(code: 'DJ', name: 'Djibouti', currencyCode: 'DJF'),
    AppCountry(code: 'DM', name: 'Dominica', currencyCode: 'XCD'),
    AppCountry(code: 'DO', name: 'Dominican Republic', currencyCode: 'DOP'),
    AppCountry(code: 'EC', name: 'Ecuador', currencyCode: 'USD'),
    AppCountry(code: 'EG', name: 'Egypt', currencyCode: 'EGP'),
    AppCountry(code: 'SV', name: 'El Salvador', currencyCode: 'USD'),
    AppCountry(code: 'GQ', name: 'Equatorial Guinea', currencyCode: 'XAF'),
    AppCountry(code: 'ER', name: 'Eritrea', currencyCode: 'ERN'),
    AppCountry(code: 'EE', name: 'Estonia', currencyCode: 'EUR'),
    AppCountry(code: 'SZ', name: 'Eswatini', currencyCode: 'SZL'),
    AppCountry(code: 'ET', name: 'Ethiopia', currencyCode: 'ETB'),
    AppCountry(code: 'FJ', name: 'Fiji', currencyCode: 'FJD'),
    AppCountry(code: 'FI', name: 'Finland', currencyCode: 'EUR'),
    AppCountry(code: 'FR', name: 'France', currencyCode: 'EUR'),
    AppCountry(code: 'GA', name: 'Gabon', currencyCode: 'XAF'),
    AppCountry(code: 'GM', name: 'Gambia', currencyCode: 'GMD'),
    AppCountry(code: 'GE', name: 'Georgia', currencyCode: 'GEL'),
    AppCountry(code: 'DE', name: 'Germany', currencyCode: 'EUR'),
    AppCountry(code: 'GH', name: 'Ghana', currencyCode: 'GHS'),
    AppCountry(code: 'GR', name: 'Greece', currencyCode: 'EUR'),
    AppCountry(code: 'GD', name: 'Grenada', currencyCode: 'XCD'),
    AppCountry(code: 'GT', name: 'Guatemala', currencyCode: 'GTQ'),
    AppCountry(code: 'GN', name: 'Guinea', currencyCode: 'GNF'),
    AppCountry(code: 'GW', name: 'Guinea-Bissau', currencyCode: 'XOF'),
    AppCountry(code: 'GY', name: 'Guyana', currencyCode: 'GYD'),
    AppCountry(code: 'HT', name: 'Haiti', currencyCode: 'HTG'),
    AppCountry(code: 'HN', name: 'Honduras', currencyCode: 'HNL'),
    AppCountry(code: 'HK', name: 'Hong Kong', currencyCode: 'HKD'),
    AppCountry(code: 'HU', name: 'Hungary', currencyCode: 'HUF'),
    AppCountry(code: 'IS', name: 'Iceland', currencyCode: 'ISK'),
    AppCountry(code: 'IN', name: 'India', currencyCode: 'INR'),
    AppCountry(code: 'ID', name: 'Indonesia', currencyCode: 'IDR'),
    AppCountry(code: 'IR', name: 'Iran', currencyCode: 'IRR'),
    AppCountry(code: 'IQ', name: 'Iraq', currencyCode: 'IQD'),
    AppCountry(code: 'IE', name: 'Ireland', currencyCode: 'EUR'),
    AppCountry(code: 'IL', name: 'Israel', currencyCode: 'ILS'),
    AppCountry(code: 'IT', name: 'Italy', currencyCode: 'EUR'),
    AppCountry(code: 'JM', name: 'Jamaica', currencyCode: 'JMD'),
    AppCountry(code: 'JP', name: 'Japan', currencyCode: 'JPY'),
    AppCountry(code: 'JO', name: 'Jordan', currencyCode: 'JOD'),
    AppCountry(code: 'KZ', name: 'Kazakhstan', currencyCode: 'KZT'),
    AppCountry(code: 'KE', name: 'Kenya', currencyCode: 'KES'),
    AppCountry(code: 'KI', name: 'Kiribati', currencyCode: 'AUD'),
    AppCountry(code: 'KP', name: 'North Korea', currencyCode: 'KPW'),
    AppCountry(code: 'KR', name: 'South Korea', currencyCode: 'KRW'),
    AppCountry(code: 'KW', name: 'Kuwait', currencyCode: 'KWD'),
    AppCountry(code: 'KG', name: 'Kyrgyzstan', currencyCode: 'KGS'),
    AppCountry(code: 'LA', name: 'Laos', currencyCode: 'LAK'),
    AppCountry(code: 'LV', name: 'Latvia', currencyCode: 'EUR'),
    AppCountry(code: 'LB', name: 'Lebanon', currencyCode: 'LBP'),
    AppCountry(code: 'LS', name: 'Lesotho', currencyCode: 'LSL'),
    AppCountry(code: 'LR', name: 'Liberia', currencyCode: 'LRD'),
    AppCountry(code: 'LY', name: 'Libya', currencyCode: 'LYD'),
    AppCountry(code: 'LI', name: 'Liechtenstein', currencyCode: 'CHF'),
    AppCountry(code: 'LT', name: 'Lithuania', currencyCode: 'EUR'),
    AppCountry(code: 'LU', name: 'Luxembourg', currencyCode: 'EUR'),
    AppCountry(code: 'MO', name: 'Macao', currencyCode: 'MOP'),
    AppCountry(code: 'MG', name: 'Madagascar', currencyCode: 'MGA'),
    AppCountry(code: 'MW', name: 'Malawi', currencyCode: 'MWK'),
    AppCountry(code: 'MY', name: 'Malaysia', currencyCode: 'MYR'),
    AppCountry(code: 'MV', name: 'Maldives', currencyCode: 'MVR'),
    AppCountry(code: 'ML', name: 'Mali', currencyCode: 'XOF'),
    AppCountry(code: 'MT', name: 'Malta', currencyCode: 'EUR'),
    AppCountry(code: 'MH', name: 'Marshall Islands', currencyCode: 'USD'),
    AppCountry(code: 'MR', name: 'Mauritania', currencyCode: 'MRU'),
    AppCountry(code: 'MU', name: 'Mauritius', currencyCode: 'MUR'),
    AppCountry(code: 'MX', name: 'Mexico', currencyCode: 'MXN'),
    AppCountry(code: 'FM', name: 'Micronesia', currencyCode: 'USD'),
    AppCountry(code: 'MD', name: 'Moldova', currencyCode: 'MDL'),
    AppCountry(code: 'MC', name: 'Monaco', currencyCode: 'EUR'),
    AppCountry(code: 'MN', name: 'Mongolia', currencyCode: 'MNT'),
    AppCountry(code: 'ME', name: 'Montenegro', currencyCode: 'EUR'),
    AppCountry(code: 'MA', name: 'Morocco', currencyCode: 'MAD'),
    AppCountry(code: 'MZ', name: 'Mozambique', currencyCode: 'MZN'),
    AppCountry(code: 'MM', name: 'Myanmar', currencyCode: 'MMK'),
    AppCountry(code: 'NA', name: 'Namibia', currencyCode: 'NAD'),
    AppCountry(code: 'NR', name: 'Nauru', currencyCode: 'AUD'),
    AppCountry(code: 'NP', name: 'Nepal', currencyCode: 'NPR'),
    AppCountry(code: 'NL', name: 'Netherlands', currencyCode: 'EUR'),
    AppCountry(code: 'NZ', name: 'New Zealand', currencyCode: 'NZD'),
    AppCountry(code: 'NI', name: 'Nicaragua', currencyCode: 'NIO'),
    AppCountry(code: 'NE', name: 'Niger', currencyCode: 'XOF'),
    AppCountry(code: 'NG', name: 'Nigeria', currencyCode: 'NGN'),
    AppCountry(code: 'MK', name: 'North Macedonia', currencyCode: 'MKD'),
    AppCountry(code: 'NO', name: 'Norway', currencyCode: 'NOK'),
    AppCountry(code: 'OM', name: 'Oman', currencyCode: 'OMR'),
    AppCountry(code: 'PK', name: 'Pakistan', currencyCode: 'PKR'),
    AppCountry(code: 'PW', name: 'Palau', currencyCode: 'USD'),
    AppCountry(code: 'PS', name: 'Palestine', currencyCode: 'ILS'),
    AppCountry(code: 'PA', name: 'Panama', currencyCode: 'PAB'),
    AppCountry(code: 'PG', name: 'Papua New Guinea', currencyCode: 'PGK'),
    AppCountry(code: 'PY', name: 'Paraguay', currencyCode: 'PYG'),
    AppCountry(code: 'PE', name: 'Peru', currencyCode: 'PEN'),
    AppCountry(code: 'PH', name: 'Philippines', currencyCode: 'PHP'),
    AppCountry(code: 'PL', name: 'Poland', currencyCode: 'PLN'),
    AppCountry(code: 'PT', name: 'Portugal', currencyCode: 'EUR'),
    AppCountry(code: 'QA', name: 'Qatar', currencyCode: 'QAR'),
    AppCountry(code: 'RO', name: 'Romania', currencyCode: 'RON'),
    AppCountry(code: 'RU', name: 'Russia', currencyCode: 'RUB'),
    AppCountry(code: 'RW', name: 'Rwanda', currencyCode: 'RWF'),
    AppCountry(code: 'KN', name: 'Saint Kitts and Nevis', currencyCode: 'XCD'),
    AppCountry(code: 'LC', name: 'Saint Lucia', currencyCode: 'XCD'),
    AppCountry(code: 'VC', name: 'Saint Vincent and the Grenadines', currencyCode: 'XCD'),
    AppCountry(code: 'WS', name: 'Samoa', currencyCode: 'WST'),
    AppCountry(code: 'SM', name: 'San Marino', currencyCode: 'EUR'),
    AppCountry(code: 'ST', name: 'São Tomé and Príncipe', currencyCode: 'STN'),
    AppCountry(code: 'SA', name: 'Saudi Arabia', currencyCode: 'SAR'),
    AppCountry(code: 'SN', name: 'Senegal', currencyCode: 'XOF'),
    AppCountry(code: 'RS', name: 'Serbia', currencyCode: 'RSD'),
    AppCountry(code: 'SC', name: 'Seychelles', currencyCode: 'SCR'),
    AppCountry(code: 'SL', name: 'Sierra Leone', currencyCode: 'SLE'),
    AppCountry(code: 'SG', name: 'Singapore', currencyCode: 'SGD'),
    AppCountry(code: 'SK', name: 'Slovakia', currencyCode: 'EUR'),
    AppCountry(code: 'SI', name: 'Slovenia', currencyCode: 'EUR'),
    AppCountry(code: 'SB', name: 'Solomon Islands', currencyCode: 'SBD'),
    AppCountry(code: 'SO', name: 'Somalia', currencyCode: 'SOS'),
    AppCountry(code: 'ZA', name: 'South Africa', currencyCode: 'ZAR'),
    AppCountry(code: 'SS', name: 'South Sudan', currencyCode: 'SSP'),
    AppCountry(code: 'ES', name: 'Spain', currencyCode: 'EUR'),
    AppCountry(code: 'LK', name: 'Sri Lanka', currencyCode: 'LKR'),
    AppCountry(code: 'SD', name: 'Sudan', currencyCode: 'SDG'),
    AppCountry(code: 'SR', name: 'Suriname', currencyCode: 'SRD'),
    AppCountry(code: 'SE', name: 'Sweden', currencyCode: 'SEK'),
    AppCountry(code: 'CH', name: 'Switzerland', currencyCode: 'CHF'),
    AppCountry(code: 'SY', name: 'Syria', currencyCode: 'SYP'),
    AppCountry(code: 'TW', name: 'Taiwan', currencyCode: 'TWD'),
    AppCountry(code: 'TJ', name: 'Tajikistan', currencyCode: 'TJS'),
    AppCountry(code: 'TZ', name: 'Tanzania', currencyCode: 'TZS'),
    AppCountry(code: 'TH', name: 'Thailand', currencyCode: 'THB'),
    AppCountry(code: 'TL', name: 'Timor-Leste', currencyCode: 'USD'),
    AppCountry(code: 'TG', name: 'Togo', currencyCode: 'XOF'),
    AppCountry(code: 'TO', name: 'Tonga', currencyCode: 'TOP'),
    AppCountry(code: 'TT', name: 'Trinidad and Tobago', currencyCode: 'TTD'),
    AppCountry(code: 'TN', name: 'Tunisia', currencyCode: 'TND'),
    AppCountry(code: 'TR', name: 'Turkey', currencyCode: 'TRY'),
    AppCountry(code: 'TM', name: 'Turkmenistan', currencyCode: 'TMT'),
    AppCountry(code: 'TV', name: 'Tuvalu', currencyCode: 'AUD'),
    AppCountry(code: 'UG', name: 'Uganda', currencyCode: 'UGX'),
    AppCountry(code: 'UA', name: 'Ukraine', currencyCode: 'UAH'),
    AppCountry(code: 'AE', name: 'United Arab Emirates', currencyCode: 'AED'),
    AppCountry(code: 'GB', name: 'United Kingdom', currencyCode: 'GBP'),
    AppCountry(code: 'US', name: 'United States', currencyCode: 'USD'),
    AppCountry(code: 'UY', name: 'Uruguay', currencyCode: 'UYU'),
    AppCountry(code: 'UZ', name: 'Uzbekistan', currencyCode: 'UZS'),
    AppCountry(code: 'VU', name: 'Vanuatu', currencyCode: 'VUV'),
    AppCountry(code: 'VA', name: 'Vatican City', currencyCode: 'EUR'),
    AppCountry(code: 'VE', name: 'Venezuela', currencyCode: 'VES'),
    AppCountry(code: 'VN', name: 'Vietnam', currencyCode: 'VND'),
    AppCountry(code: 'YE', name: 'Yemen', currencyCode: 'YER'),
    AppCountry(code: 'ZM', name: 'Zambia', currencyCode: 'ZMW'),
    AppCountry(code: 'ZW', name: 'Zimbabwe', currencyCode: 'ZWG'),
  ];

  static AppCurrency byCode(String code) {
    return currencies.firstWhere(
      (c) => c.code == code,
      orElse: () => AppCurrency(code: code, symbol: code, name: code),
    );
  }

  static AppCountry? countryByCode(String code) {
    for (final country in countries) {
      if (country.code == code) return country;
    }
    return null;
  }

  static List<AppCountry> searchCountries(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return countries;
    return countries
        .where(
          (c) =>
              c.name.toLowerCase().contains(q) ||
              c.code.toLowerCase().contains(q) ||
              c.currencyCode.toLowerCase().contains(q),
        )
        .toList();
  }

  static List<AppCurrency> searchCurrencies(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return currencies;
    return currencies
        .where(
          (c) =>
              c.name.toLowerCase().contains(q) ||
              c.code.toLowerCase().contains(q) ||
              c.symbol.toLowerCase().contains(q),
        )
        .toList();
  }
}
