// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsuK0AH8t16OMiISVNnw0GLIyqKwl5WgI',
    appId: '1:963502909808:android:644446d146ffb3962247b5',
    messagingSenderId: '963502909808',
    projectId: 'shop-management-42ce1',
    storageBucket: 'shop-management-42ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTrXMHKQiyGczlhhKKH5LOcJEd_nbua8',
    appId: '1:963502909808:ios:587159597b144b4d2247b5',
    messagingSenderId: '963502909808',
    projectId: 'shop-management-42ce1',
    storageBucket: 'shop-management-42ce1.firebasestorage.app',
    iosBundleId: 'com.example.nkt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoz6Yl5him9p_O8aS3wm4JeTR5a0sHh7I',
    appId: '1:963502909808:web:75a2ffaae2eb1f342247b5',
    messagingSenderId: '963502909808',
    projectId: 'shop-management-42ce1',
    authDomain: 'shop-management-42ce1.firebaseapp.com',
    storageBucket: 'shop-management-42ce1.firebasestorage.app',
    measurementId: 'G-VTWCKRLCJW',
  );
}
